server:
  port: 8080
  servlet:
    session:
      timeout: ${REDIS_TIMEOUT}

spring:
  application:
    name: app1
  profiles:
    active: dev
# 메일 설정
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_SMTP_AUTH}
          timeout: ${EMAIL_SMTP_TIMEOUT}
          starttls: 
            enable: ${EMAIL_SMTP_ENABLE}
# ENV 설정
  config:
    import: optional:file:.env[.properties]
# database 설정
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
# Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}
# Spring Session 설정
  session:
#    store-type: redis
    redis:
      repository-type: default
      flush-mode: immediate
      namespace: ${REDIS_NAMESPACE}
# file size 설정
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# 보안 설정
  security:
    csrf:
      enabled: true   # CSRF 보호 활성화
    user:
      name: user  # 기본 사용자 이름
      password: password  # 기본 비밀번호 설정


# log level 설정
logging:
  level:
    org:
      springframework:
        web: INFO
      thymeleaf: INFO